### ISSUE TITLE
NPM package version

### ISSUE THREAD

**Issue by nikitaeverywhere** [ljharb/istanbul-merge#42]
Hello @ljharb! Thanks for a handy tool.

I noticed the source code in this repo is regularly updated, while the NPM package stays super old.

![image](https://user-images.githubusercontent.com/4989256/228306414-768433aa-44f0-444c-b70b-2214e9792575.png)

Can you publish the newest version please? In particular, I am interested in updating istanbul dependency, since it's hardcoded. They generate nicer HTML now :)

**Comment by ljharb** [comment]
The last released version of istanbul-merge, v1.1.1, indeed depends on v1 of istanbul-lib-coverage, while the default branch depends on v2. I'll try to get this in a releaseable state.

**Comment by ljharb** [comment]
v2 has been published.

**Comment by nikitaeverywhere** [comment]
Thanks a ton!
